version: "3.8"

services:
  golang-study:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: golang-study
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: ["go", "run", "cmd/app/server.go"]
    environment:
      - DB_HOST=db
      - DB_PORT=${POSTGRES_DB_PORT}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=${POSTGRES_DB}
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
